// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * List
       * @returns {Promise<Array<models.heic>>}  - Go Type: []main.heic
       */
      "List": () => {
        return window.go.main.App.List();
      },
      /**
       * WorkFile
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "WorkFile": (arg1) => {
        return window.go.main.App.WorkFile(arg1);
      },
    },
  },

};
export default go;
