// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Greet
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": () => {
        return window.go.main.App.Greet();
      },
    },
  },

};
export default go;
